services:
  backend:
    image: generaltao725/gentool-data-viewer-backend:latest
    environment:
      JDK_JAVA_OPTIONS: --add-opens java.base/java.lang=ALL-UNNAMED
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      POSTGRES_APP_USER: ${POSTGRES_APP_USER:?POSTGRES_APP_USER must be set}
      POSTGRES_APP_PASSWORD: ${POSTGRES_APP_PASSWORD:?POSTGRES_APP_PASSWORD must be set}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID:?DISCORD_CLIENT_ID must be set}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET:?DISCORD_CLIENT_SECRET must be set}
      CONSOLE_OWNER_DISCORD_IDS:
      CONSOLE_ADMIN_DISCORD_IDS:
#      LOGGING_LEVEL_ROOT: TRACE
#      LOGGING_LEVEL_ORG_TAONITY_GENTOOLDATAVIEWER: DEBUG
    command: --spring.profiles.active=${SPRING_PROFILES_ACTIVE:?SPRING_PROFILES_ACTIVE must be set}
    volumes:
      - ./config:/gentool-data-viewer/config
    healthcheck:
      test: curl localhost:8080/actuator/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 100