services:
  flyway:
    image: flyway/flyway:10.18.0
    command: migrate
    environment:
      FLYWAY_PLACEHOLDER_PREFIX: "{{ "
      FLYWAY_PLACEHOLDER_SUFFIX: " }}"
      POSTGRES_ADDRESS: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: gentool_data_viewer_db
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER must be set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD must be set}
      POSTGRES_APP_USER: ${POSTGRES_APP_USER:?POSTGRES_APP_USER must be set}
      POSTGRES_APP_PASSWORD: ${POSTGRES_APP_PASSWORD:?POSTGRES_APP_PASSWORD must be set}
    volumes:
      - ./flyway.conf:/flyway/conf/flyway.conf
      - ./sql:/flyway/sql