server:
  servlet:
    session:
      cookie:
        domain: taonity.org
        name: JSESSIONID-GENTOOL-DATA-VIEWER-PROD

app:
  default-success-url: https://gentool-data-viewer.taonity.org
  login-url: https://gentool-data-viewer.taonity.org
  csrf-cookie-name: XSRF-TOKEN-GENTOOL-DATA-VIEWER-PROD